# Generated by Django 3.1.3 on 2020-11-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201128_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdby_id',
            field=models.IntegerField(),
        ),
    ]
